before_install:
- openssl aes-256-cbc -K $encrypted_190138481d11_key -iv $encrypted_190138481d11_iv
  -in deploy_key.enc -out ./deploy_key -d
- chmod 600 deploy_key
- ssh-add ./deploy_key

deploy:
  provider: script
  script: bash frontend/deploy.sh
  on:
    branch: develop
