language: node_js
node_js:
 - "node"
before_script:
- cd frontend
- npm install
script:
- npm run build
addons:
  ssh_known_hosts: dev.professornot.com
before_deploy:
- cd ..
- openssl aes-256-cbc -K $encrypted_190138481d11_key -iv $encrypted_190138481d11_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add ./deploy_key
- cd frontend
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: develop
