# Generated by Django 2.2.6 on 2019-11-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
            options={
                'unique_together': {('name', 'school')},
            },
        ),
    ]
