# Generated by Django 2.2.6 on 2019-11-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('coursename', 'school')},
        ),
    ]
