# Generated by Django 2.2.6 on 2019-11-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('courses', '0002_auto_20191107_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'school')},
        ),
    ]
