# Generated by Django 2.2.6 on 2019-11-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('courses', '0003_auto_20191107_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_name', 'school')},
        ),
    ]
