# Generated by Django 2.2.6 on 2019-11-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('courses', '0004_auto_20191107_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'school')},
        ),
    ]
