# Generated by Django 2.2.5 on 2019-09-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='def', max_length=69),
            preserve_default=False,
        ),
    ]
