# Generated by Django 3.0.3 on 2020-02-17 16:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizquestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(max_length=2),
        ),
    ]
