# Generated by Django 3.0.3 on 2020-02-18 15:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('quiz', '0006_auto_20200217_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponses',
            fields=[
                ('reviewer', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='QuizResponses', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('responses', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
    ]
