# Generated by Django 3.0.3 on 2020-02-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizresponses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresponses',
            old_name='reviewer',
            new_name='user',
        ),
    ]
